### ISSUE TITLE
feature request - stock status

### ISSUE THREAD

**Issue by Janso9295** [coderpaddy/e-pet-discount-products#3]
Is there any way you can make the scraper tell me if a product is sold out or not please?

**Comment by Janso9295** [comment]
This is giving me an error

`Traceback (most recent call last):
  File "scrape.py", line 43, in <module>
    writer.writerow(product_dict)
  File "C:\Users\Right Click\AppData\Local\Programs\Python\Python38-32\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Users\Right Click\AppData\Local\Programs\Python\Python38-32\lib\csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'stock'`

**Comment by coderpaddy** [comment]
This issue should be resolved now, apologies for the delay

**Comment by Janso9295** [comment]
Now I've got this problem 

`Traceback (most recent call last):
  File "scrape.py", line 3, in <module>
    from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'`

**Comment by coderpaddy** [comment]
did you use an env originally?

**Comment by Janso9295** [comment]
no I never have, though this time I copied and pasted it all in - could that be what's causing the issue?

**Comment by coderpaddy** [comment]
im not sure, just delete the folder, then in terminal:

`git clone https://github.com/coderpaddy/e-pet-discount-products.git`
`cd e-pet-discount-products`
`pip install -r requirements.txt`
`python scrape.py`

**Comment by Janso9295** [comment]
I now have this error 

`Traceback (most recent call last):
  File "scrape.py", line 14, in <module>
    total_num_pages = website.html.search('<li class="pagination__text">\n    Page 1 of {total_num_pages}\n  </li>')['total_num_pages']
TypeError: 'NoneType' object is not subscriptable`

**Comment by coderpaddy** [comment]
ooh, still dog-food-dry? ill test again fully :D

**Comment by Janso9295** [comment]
oh sorry no I'm trying categories at random this one was bird-cages - I went with one that was small but had out of stock items, so I could quickly test

**Comment by coderpaddy** [comment]
Okay, try one more time, i reckon that should be it, it works for 1 page resuts and multipage results,

i tried bird-cages and dog-food-dry both scraped perfect with stock check

**Comment by Janso9295** [comment]
Thanks, that works. Is it possible to make it express the answer as a 1 or a 0 accordingly?

**Comment by coderpaddy** [comment]
Just to confirm 1 for in stock 0 out of stock
I will make this change

**Comment by coderpaddy** [comment]
Fixed, just clone the master branch, all features requested are on.

**Comment by Janso9295** [comment]
Yes that's right, thanks I'll give it a go
